version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: limpiezasduo
      DB_USERNAME: limpiezasduo
      DB_PASSWORD: secret
    depends_on:
      - db
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - app
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: limpiezasduo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: limpiezasduo
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
